using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Maui.FormBuilder.Builder;
using Microsoft.Maui.Controls;

namespace Maui.FormBuilder.Sample.Pages;

/// <summary>
/// Demonstrates loading a registration form from a JSON schema.
/// The entire form UI — fields, labels, actions — is generated by MauiFormBuilder.
/// </summary>
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();

        // Only build once
        if (Content is not null && Content is not Microsoft.Maui.Controls.ScrollView)
            return;

        this.Content = await BuildRegistrationFormAsync();
    }

    // ── Form Construction ──────────────────────────────────────────────────

    private async Task<View> BuildRegistrationFormAsync()
    {
        string json = await LoadSchemaAsync("registration.json");

        return new MauiFormBuilder()
            .LoadFromJson(json)
            .OnSubmit(HandleSubmit)
            .Build();
    }

    private async void HandleSubmit(System.Collections.Generic.Dictionary<string, object?> data)
    {
        var sb = new StringBuilder();
        foreach (var (key, value) in data)
        {
            string display = value switch
            {
                string[] arr  => string.Join(", ", arr),
                null          => "(empty)",
                _             => value.ToString() ?? "(empty)"
            };
            sb.AppendLine($"• {key}: {display}");
        }

        await DisplayAlert("✅ Form Submitted", sb.ToString(), "OK");
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private static async Task<string> LoadSchemaAsync(string fileName)
    {
        await using Stream stream = await FileSystem.OpenAppPackageFileAsync(fileName);
        using var reader = new StreamReader(stream);
        return await reader.ReadToEndAsync();
    }
}
